services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - yuyuwechatv2_network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: tykWyr-bepqu6-fafvym
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks:
      - yuyuwechatv2_network

  yuyuwechatv2_client:
    build: .
    container_name: yuyuwechatv2_client
    ports:
      - "7500:7500"
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=tykWyr-bepqu6-fafvym
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5431
    networks:
      - yuyuwechatv2_network

networks:
  yuyuwechatv2_network:
    driver: bridge